INPUT_TXT=../data/txt/teste3.txt
INPUT_JSON=../data/json/grafo.json
INPUT_SALESMAN=../data/tsp/d198.tsp

MAIN = main.py

all:
	python3 $(MAIN) -o $(INPUT_TXT)

windows:
	python main.py -o ../data/teste3.txt